### ISSUE TITLE
[Feature Request] when draw lines, use middle scroll button to change the line width. 

### ISSUE THREAD

**Issue by hclewk** [hclewk/ShareX#1]
When I draw a line, I should be able to use the scroll wheel to increase or decrease the line width.
Also, after I draw a line, I should be able to select the line and use the scroll wheel change the line width.

**Comment by ai-taco** [comment]
Starting work on this issue.
You can follow along at the following link:
http://demo01.recursiveai.io/client-log-viewer.html?id=20241107181044-ijbIJBUUMChWAd5z

**Comment by ai-taco** [comment]
Work on this issue has been completed, and a Pull Request has been made.

**Comment by hclewk** [comment]
try again

**Comment by ai-taco** [comment]
Starting work on this issue.
You can follow along at the following link:
http://demo01.recursiveai.io/client-log-viewer.html?id=20241107185106-tYsPy6ocH6BVWexF
